version: "3.8"
services: 
    app:
        build:
            context: .
        volumes:
            - .:/my-app
        ports:
            - 3000:3000
        image: app:react
        container_name: pomo_app_container
        command: npm start